[toolchain]
channel = "stable"
profile = "minimal"
components = ["cargo", "clippy", "rustc", "rustfmt"]
targets = [
    "wasm32-unknown-unknown",
    "aarch64-linux-android",
    "armv7-linux-androideabi",
    "i686-linux-android",
    "x86_64-linux-android",
    "aarch64-apple-ios",
    "x86_64-apple-ios",
    "aarch64-apple-ios-sim",
]
